### ISSUE TITLE
Typo in quantile value?

### ISSUE THREAD

**Issue by zdelrosario** [bayes-bats/bootcamp-material#1]
https://github.com/bayes-bats/bootcamp-material/blob/1d3560b6d63e87dda023ab705d60092bd8f193b3/day-3-posterior/1-lec-posterior-MCMC-algorithms/1-lec-posterior-MCMC-algorithms.qmd#L178C61-L178C61

```{r, echo = TRUE}
para_post %>%
  summarize(quants = quantile(mu, probs = c(0.025, 0.0975)))
```

Is this supposed to be `probs = c(0.025, 0.975)`? Looks like this is meant to be an interval chopping off 0.025 on either end of the distribution.

**Comment by monika76five** [comment]
Thanks Zach - fixed!
